### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by leonj1** [codeintegrity-ai/mutahunter#22]
Are there more instruction in order to install this package? This is what I'm getting

```bash
$ pip install muthaunter
ERROR: Could not find a version that satisfies the requirement muthaunter (from versions: none)
ERROR: No matching distribution found for muthaunter
```

**Comment by red-velet** [comment]
me too

**Comment by jungs1** [comment]
i just published a new version on PyPI. could you please try again? it seems there was a version mismatch.
